### ISSUE TITLE
"visible()" returns "true" for an element outside visible viewport when its CSS "display" property is "none"

### ISSUE THREAD

**Issue by PanzerKunst** [customd/jquery-visible#21]
Can something be done about that?

_Note:_
This was only reproduced using _jquery.visible.min.js_ (on master). Using _jquery.visible.js_ returns `false`.

**Comment by BoboTiG** [comment]
:+1:  It took me hours to find this behavior, it was bugging my WordPress theme.

**Comment by samatcd** [comment]
This can be very easily done by adding `.is(':visible')` selector before calling this plugin. Docs explain that this is outside of the scope of this plugin.
