### ISSUE TITLE
Element is not detected as visible if its top and bottom extend outside the bounds of the view

### ISSUE THREAD

**Issue by VizualAbstract** [customd/jquery-visible#22]
Say the window is 600px tall, but the element we're calling visible() on is 800px tall (larger than the window itself), so while scrolling, at a certain point, the very top and bottom of the element is hidden from view...

Visible() returns false when the element is in this state- visible in the window, but it's top and bottom edges are out of bounds.

**Comment by jsjohns** [comment]
I'm seeing the same behavior with version 1.2.0 (tested on Chrome 44.0, Fedora 22).

**Comment by Klayemore** [comment]
I've just noticed this issue as well. I'm using jQuery Visible for parallax-like effects when divs are in the viewport.

However when a div is higher than the viewport, and the top and bottom are out of view, visibility is false.

Looking forward to a solution.

Cheers,
Klaye

**Comment by ut** [comment]
I've noticed this issue as well (Version 1.2.0 with Firefox 39, Win64 + Ubuntu)

**Comment by samatcd** [comment]
Resolved in latest commit.
