### ISSUE TITLE
Non-JQuery version?

### ISSUE THREAD

**Issue by aliakhtar** [customd/jquery-visible#24]
Hey there,

It would be fantastic if this plugin could be made to work without the jquery dependency. The plugin itself is only 3kb or so, it doesn't make sense to have to include the 40-50kb of jquery code just to use it.

Any thoughts?

**Comment by samatcd** [comment]
This is the project where the actual number formatting part comes from: http://phpjs.org/functions/number_format/

You're welcome to use the code and strip out jQuery event handling etc for your own version, but we have no use for that in our projects, as jQuery is included for other reasons anyway, so it's unlikely to be done by any of our team.
