### ISSUE TITLE
iPhone / mobile safari - view port hight wrong

### ISSUE THREAD

**Issue by lpas** [customd/jquery-visible#25]
the vpHeight is wrong in IPhone's mobile safari 

http://bugs.jquery.com/ticket/6724

fix line#22

```
vpHeight  = window.innerHeight ? window.innerHeight : $w.height(), 
```

**Comment by samatcd** [comment]
As per link in the bug, make sure you have a valid doctype: http://viralpatel.net/blogs/jquery-window-height-incorrect/
