### ISSUE TITLE
New release needed.

### ISSUE THREAD

**Issue by austinpray** [customd/jquery-visible#28]
There needs to be a new release that includes https://github.com/customd/jquery-visible/commit/4668a5e2ace563ce3944b2f6993017865e576f02

This is causing trouble for people: https://discourse.roots.io/t/installing-jquery-visible-plugin-with-bower

**Comment by samatcd** [comment]
Fixed by 1.2.0 tag.

**Comment by DanielRuf** [comment]
Can we make a new release?

**Comment by DanielRuf** [comment]
PS
```shell
bower invalid-meta  The "description" is too long, the limit is 140 characters
```
