### ISSUE TITLE
List on npm?

### ISSUE THREAD

**Issue by TerribleDev** [customd/jquery-visible#34]
Could you list this on npm (or just link me to it, if it already is) for those of us using browserify?

**Comment by AlexKovalevych** [comment]
+1

**Comment by phun-ky** [comment]
+1

**Comment by kspearrin** [comment]
+1

**Comment by mango-jason** [comment]
+1

**Comment by samatcd** [comment]
Hey, thanks for the support on this feature. I'll take a look at adding support. If someone could point me at an example or some documentation for how this should work I'd be grateful – would save some time in digging around 😃

**Comment by renanborgez** [comment]
+1

**Comment by andydust** [comment]
+1

**Comment by lukasjuhas** [comment]
+1

**Comment by lukasjuhas** [comment]
@samatcd [https://gist.github.com/coolaj86/1318304](https://gist.github.com/coolaj86/1318304)

**Comment by chrisgeary92** [comment]
👍

**Comment by chrisgeary92** [comment]
+1

**Comment by dcalhoun** [comment]
@samatcd it would appear you have the proper `package.json` setup in the repository. You should be able to run [`npm publish`](https://docs.npmjs.com/getting-started/publishing-npm-packages) to publish this package to https://www.npmjs.com. Would you be willing to publish soon, please?

**Comment by samatcd** [comment]
Done.
