### ISSUE TITLE
jquery.visible vs jquery-visible

### ISSUE THREAD

**Issue by et** [customd/jquery-visible#44]
We had a bower entry for `"jquery.visible": "1.1.0"` which used to point to this repository. Now it seems to be pointing to this [other repository](https://github.com/teamdf/jquery-visible) which clearly doesn't do the same behavior.

The fix was pretty easy, change `"jquery.visible": "1.1.0"` to `"jquery-visible": "1.1.0"`, however we want to see if this is a result of a hijacked package, bower inferring dots (.) as dashes (-), or something else.

**Comment by samatcd** [comment]
This is an issue with Bower/GitHub. We migrated our account from `teamdf` to `customd`— our original testing showed that stuff was automatically redirected to the new account, but GitHub seem to have made our old handle available since.
